# Site settings
title: Katherine Kampf
description: Product Manager
baseurl: "/"
url: acrokat.github.io

# User settings
username: acrokat
user_description: Test
user_title: Product Manager
email: kvkampf@gmail.com
twitter_username: hardworkingpm
github_username:  acrokat
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
