# Site settings
title: katherine kampf
description: product manager
# baseurl: "/"
url: acrokat.me

# User settings
username: katherine kampf
user_description: Product Manager passionate about connecting people through technology. Previous experience with EdTech, Big Data, AI, gaming, and Python.
user_title: product manager - acrokat
email: kvkampf@gmail.com
twitter_username: hardworkingpm
github_username:  acrokat
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
