# Site settings
title: Katherine Kampf
description: Product Manager
# baseurl: "/"
url: acrokat.me

# User settings
username: Katherine Kampf
user_description: Product Manager passionate about connecting people through technology. <br> Previous experience with EdTech, Big Data, AI, gaming, and Python.
user_title: product manager - acrokat
email: kvkampf@gmail.com
twitter_username: acrokatto
github_username:  acrokat

# Google-analytics
google-analytics:
  id: "G-4VNKH7V8X7"

exclude: ['package.json', 'src' , 'node_modules']
